SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;



CREATE TABLE IF NOT EXISTS `brand` (
  `idBrand` smallint(6) NOT NULL,
  `name` char(100) DEFAULT NULL,
  PRIMARY KEY (`idBrand`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



INSERT INTO `brand` (`idBrand`, `name`) VALUES
(2, 'ACURA'),
(3, 'ALFA ROMEO'),
(4, 'AUDI'),
(5, 'BAIC'),
(6, 'BMW'),
(7, 'BUICK'),
(8, 'CADILLAC'),
(9, 'CBO MOTORS'),
(10, 'CHEVOLET'),
(11, 'CHRYSLER'),
(12, 'DODGE'),
(13, 'FAW'),
(14, 'FERRARI'),
(15, 'FIAT'),
(16, 'FORD'),
(17, 'GIANT'),
(18, 'GMC'),
(19, 'HONDA'),
(20, 'HUMMER'),
(21, 'HYUNDAI'),
(22, 'INFINITI'),
(23, 'JAGUAR'),
(24, 'JEEP'),
(25, 'KIA'),
(26, 'LAND ROVER'),
(27, 'LINCOLN'),
(28, 'MAZDA'),
(29, 'MASTRETTA'),
(30, 'MASERATI'),
(31, 'MERCEDES BENZ'),
(32, 'MERCURY'),
(33, 'MG'),
(34, 'MINI'),
(35, 'MITSUBISHI'),
(36, 'NISSAN'),
(37, 'PEUGEOT'),
(38, 'PONTIAC'),
(39, 'PORSCHE'),
(40, 'RENAULT'),
(41, 'ROVER'),
(42, 'SAAB'),
(43, 'SEAT'),
(44, 'SMART'),
(45, 'SUBARU'),
(46, 'SUZUKI'),
(47, 'TOYOTA'),
(48, 'VOLKSWAGEN'),
(49, 'VOLVO'),
(50, 'HINO'),
(51, 'SPARTAK'),
(52, 'TESLA MOTORS'),
(53, 'MOTOCICLETA');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
